# Verify owner and repo first
owner: fullprofile # Your GitHub organization or username, where this repository lives
repo: agridigital-status-monitor # The name of this repository

sites:
  - name: AgriDigital App
    url: https://app.agridigital.io/
  - name: OUS Service
    url: https://ous.agridigital.io/api/_organisations/heartbeat
  - name: API Service
    url: https://api.agridigital.io/api/v1/values/TestDbQuery
  - name: Xero Integration
    url: https://xero.agridigital.io/health
  - name: NGR System Status
    url: https://my.ngr.com.au/api/v2/web_service/service_test
  - name: AgriDigital Short URL Service
    url: agri.digital 
  - name: Cache Service
    url: $CACHE_URL
    headers:
      - "Authorization: Basic $ELASTIC_SECRET"
      - "Content-Type: application/json"
  - name: SMS Broadcast Service
    url: https://api.smsbroadcast.com.au/api-adv.php

assignees:
  - mccpanelo-ad

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.agridigital.io  # Custom CNAME
  #baseUrl: /agridigital-status-monitor
  logoUrl: https://agridigital-public-media.s3.us-east-2.amazonaws.com/media/AgriDigital_Lockup_Horizontal_Colour.png
  name: AgriDigital Status Monitor
  introTitle: "AgriDigital Status Monitor provides a quick look at our services and the uptime"
  navbar:
    - title: Status
      href: /
    - title: AgriDigital App
      href: https://app.agridigital.io/
    - title: Knowledge Base
      href: https://knowledgebase.agridigital.io/
    
i18n:
  footer: Grown by AgriDigital

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration