name: AD1 Banner Maintenance

on:
  issues:
    types: [opened, closed]
  workflow_dispatch:

jobs:
  create_issue:
    name: Create issue on agridigital repo
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v6
        if: ${{ github.event.issues.title }}
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            await github.rest.issues.create({
              owner: 'fullprofile',
              repo: 'agridigital',
              title: ${{ github.event.issues.title }},
              body: ${{ github.event.issues.body }},
              labels: [],
            });
