name: AD1 Banner Maintenance

on:
  issues:
    types: [opened, closed]
  workflow_dispatch:

jobs:
  create_issue:
    name: Create issue on agridigital repo
    runs-on: ubuntu-18.04
    if: ${{ github.event.action == 'opened' }}

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - uses: actions/checkout@v2

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            await github.rest.issues.create({
              owner: 'fullprofile',
              repo: 'agridigital',
              // github.event.issue.id will be used to search when closing the issue
              title: '${{ github.event.issue.title }} - ${{ github.event.issue.id }} ',
              body: '${{ github.event.issue.body }}',
              labels: ['BANNER', 'CUSTOM OUTAGE MESSAGE'],
            });

  close_issue:
    name: Close issue on agridigital repo
    runs-on: ubuntu-18.04
    if: ${{ github.event.action == 'closed' }}

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - uses: actions/checkout@v2

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            // Fetch all issues on agridigital repo with filter
            const issues = await github.rest.issues.listForRepo({
              owner: 'fullprofile',
              repo: 'agridigital',
              labels: ['BANNER', 'CUSTOM OUTAGE MESSAGE'], // Filter issues with banner label
              state: 'open', // Filter open issues
            });

            // Extract the related issue created by issue from agridigital-status-monitor
            const linkedIssue = issues.data.find(i => i.title.includes('${{ github.event.issue.id }}'));

            // Update agridigital issue to close
            await github.rest.issues.update({
              owner: 'fullprofile',
              repo: 'agridigital',
              issue_number: linkedIssue.number,
              state: 'closed'
            });
